

### Delete UserGroup with ID *
DELETE {{host}}}/api/UserGroup/1
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
    client.test("Delete UserGroup request executed successfully", function() {
        client.assert(response.status === 204, "Response status is not 204");
    });
%}


### Create UserGroup
POST {{host}}/api/UserGroup
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "UserId": "{{mehmet_id1}}",
  "GroupId": 2
}

> {%
    client.test("POST UserGroup request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

