

### Get all Expenses
GET {{host}}/api/Expense
Accept: application/json

> {%
    client.log("Token from env: " + client.global.get("auth_token"));
    client.test("Get All Expenses request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Get Expense with ID *
GET {{host}}/api/Expense/11
Accept: application/json

> {%
    client.test("Get Expense request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Update Expense with ID *
PUT {{host}}/api/Expense/2
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "Id": 2,
  "Name": "subway",
  "Description": "sandwich that is nice",
  "Amount": "6.72",
  "Category": "food",
  "GroupId": 2
}

> {%
    client.test("Put Expense request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Delete Expense with ID *
DELETE {{host}}/api/Expense/1
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
    client.test("Delete Expense request executed successfully", function() {
        client.assert(response.status === 204, "Response status is not 204");
    });
%}
