


### Create Expense
POST {{host}}/api/Expense
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "Id": 0,
  "Name": "dollartree",
  "Description": "cookies",
  "Amount": "1.07",
  "Category": "cheap crap",
  "GroupId": 2
}

> {%
    client.test("Post Expense request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}



### Create Expense
POST {{host}}/api/Expense
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "Id": 0,
  "Name": "dollartree",
  "Description": "cookies",
  "Amount": "1.07",
  "Category": "cheap crap",
  "GroupId": 2
}

> {%
    client.test("Post Expense request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}



### Create Expense
POST {{host}}/api/Expense
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "Id": 0,
  "Name": "dollartree",
  "Description": "cookies",
  "Amount": "1.07",
  "Category": "cheap crap",
  "GroupId": 2
}

> {%
    client.test("Post Expense request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}



### Create Expense
POST {{host}}/api/Expense
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "Id": 0,
  "Name": "dollartree",
  "Description": "cookies",
  "Amount": "1.07",
  "Category": "cheap crap",
  "GroupId": 2
}

> {%
    client.test("Post Expense request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}



### Create Expense
POST {{host}}/api/Expense
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "Id": 0,
  "Name": "dollartree",
  "Description": "cookies",
  "Amount": "1.07",
  "Category": "cheap crap",
  "GroupId": 2
}

> {%
    client.test("Post Expense request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}



### Create Expense
POST {{host}}/api/Expense
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "Id": 0,
  "Name": "dollartree",
  "Description": "cookies",
  "Amount": "1.07",
  "Category": "cheap crap",
  "GroupId": 2
}

> {%
    client.test("Post Expense request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

