


### Get all Groups
GET {{host}}/api/Group
Accept: application/json

> {%
    client.test("Get All Groups request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Get Group with ID *
GET {{host}}/api/Group/2
Accept: application/json

> {%
    client.test("Get Group request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Update Group with ID *
PUT {{host}}/api/Group/2
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "Id": 2,
  "Name": "banana hannah"
}

> {%
    client.test("PUT Group request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}


### Create Group
POST {{host}}/api/Group
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "Id": 0,
  "Name": "freshyclub"
}

> {%
    client.test("POST Group request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}


### Delete Group with ID *
DELETE {{host}}}/api/Group/1
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
    client.test("Delete Group request executed successfully", function() {
        client.assert(response.status === 204, "Response status is not 204");
    });
%}
